SELECT

 CN9.R_E_C_N_O_ CN9_REC
,SA1.R_E_C_N_O_ SA1_REC
,SA1.A1_CGC
,SA1.A1_PFISICA
,SA1.A1_DDD
,SA1.A1_TEL
,SA1.A1_NREDUZ
,SA1.A1_NOME
,SA1.A1_CONTATO
,SA1.A1_EMAIL
,SA1.A1_DTNASC
,SA1.A1_XEND
,SA1.A1_COMPLEM
,SA1.A1_XNR_END
,SA1.A1_MUN
,SA1.A1_BAIRRO
,SA1.A1_CEP
,SA1.A1_EST
,SYA.YA_SIGLA

,CNA.R_E_C_N_O_ CNA_REC 
,CNA.CNA_DTINI
,CNA.CNA_DTFIM
,CNA.CNA_XDIAS
,( SELECT TOP 1 X5_DESCRI FROM %TABLE:SX5% SX5 
	WHERE SX5.%NOTDEL% AND SX5.X5_TABELA = 'Z1' 
	AND SX5.X5_CHAVE = CNA.CNA_XTIPO 
	AND SX5.X5_FILIAL = %XFILIAL:SX5% ) CNA_XTIPON
,CNA.CNA_XJUROS
,CNA.CNA_XANTAU
,CNA.CNA_XMXANT
,CNA.CNA_XPADIA
,CNA.CNA_XPGUNI
,CNA.CNA_XPRCUN
,CNA.CNA_XQTFIX
,CNA.CNA_XANTDI

,CNB.CNB_XPCINI
,CNB.CNB_XPCFIN
,CNB.CNB_XESQTX
,( SELECT TOP 1 X5_DESCRI FROM %TABLE:SX5% SX5
	WHERE SX5.%NOTDEL% AND SX5.X5_TABELA = 'Z2' 
	AND SX5.X5_CHAVE = CNB.CNB_XTPCAR 
	AND SX5.X5_FILIAL = %XFILIAL:SX5% ) CNB_XTPCAN
,CNB.CNB_XQTFIX
,CNB.CNB_XDIAS

FROM %TABLE:CN9% CN9

INNER JOIN %TABLE:CNA% CNA
ON  CN9.CN9_FILIAL = CNA.CNA_FILIAL
AND CN9.CN9_NUMERO = CNA.CNA_CONTRA
AND CN9.CN9_REVISA = CNA.CNA_REVISA
AND CN9.D_E_L_E_T_ = CNA.D_E_L_E_T_

INNER JOIN %TABLE:CNB% CNB
ON  CNA.CNA_FILIAL = CNB.CNB_FILIAL
AND CNA.CNA_CONTRA = CNB.CNB_CONTRA
AND CNA.CNA_REVISA = CNB.CNB_REVISA
AND CNA.D_E_L_E_T_ = CNB.D_E_L_E_T_

INNER JOIN %TABLE:SA1% SA1
ON  CNA.CNA_CLIENT = SA1.A1_COD
AND CNA.CNA_LOJACL = SA1.A1_LOJA
AND CNA.D_E_L_E_T_ = CNA.D_E_L_E_T_

LEFT JOIN %TABLE:SYA% SYA
ON  SA1.A1_PAIS = SYA.YA_CODGI
AND SA1.D_E_L_E_T_ = SYA.D_E_L_E_T_

WHERE CN9.CN9_FILIAL = %XFILIAL:CN9% 
AND CN9.CN9_SITUAC = '05'
AND CN9.%NOTDEL%
AND SA1.A1_FILIAL  = %XFILIAL:SA1%
AND ( CN9.CN9_XENVID = '2' OR SA1.A1_XENVIAD = '2' )

ORDER BY SA1.R_E_C_N_O_, CNA.R_E_C_N_O_, CNB.R_E_C_N_O_