--? cCompetenc := '022023'
--? cEspCtr := '2'

SELECT

CN9.CN9_NUMERO, CN9.CN9_REVISA, CN9.CN9_XCDPMD,
CNA.CNA_NUMERO, CNA.CNA_XPLHRE, 
CNB.CNB_ITEM, CNB.CNB_PRODUT, CNB.CNB_QUANT, CNB.CNB_VLUNIT, CNB.CNB_XHREXT, 

CASE CN9_ESPCTR

	WHEN '1' THEN CNB.CNB_TE 
	WHEN '2' THEN CNB.CNB_TS
	ELSE ''

END CNE_TES,

SZC.ZC_TOTHRS 

FROM %TABLE:SZC% SZC

INNER JOIN %TABLE:SZA% SZA
ON  SZA.D_E_L_E_T_ = SZC.D_E_L_E_T_
AND SZA.ZA_FILIAL  = SZC.ZC_FILIAL
AND SZA.ZA_CODIGO  = SZC.ZC_TAREFA

INNER JOIN %TABLE:CN9% CN9
ON  SZA.D_E_L_E_T_ = SZC.D_E_L_E_T_
AND SZA.ZA_FILIAL  = CN9.CN9_FILIAL
AND ( 
	CN9.CN9_ESPCTR  = '1' AND SZA.ZA_RECCTR  = CN9.CN9_NUMERO OR
	CN9.CN9_ESPCTR  = '2' AND SZA.ZA_CLICTR  = CN9.CN9_NUMERO
	)
AND ( 
	CN9.CN9_ESPCTR  = '1' AND SZA.ZA_RECRVCT  = CN9.CN9_REVISA OR
	CN9.CN9_ESPCTR  = '2' AND SZA.ZA_CLIRVCT  = CN9.CN9_REVISA
	)

INNER JOIN %TABLE:CNA% CNA
ON  CN9.D_E_L_E_T_  = CNA.D_E_L_E_T_
AND CN9.CN9_FILIAL  = CNA.CNA_FILIAL
AND CN9.CN9_NUMERO  = CNA.CNA_CONTRA
AND CN9.CN9_REVISA  = CNA.CNA_REVISA
AND ( 
	CN9.CN9_ESPCTR  = '1' AND SZA.ZA_RECPLAN  = CNA.CNA_NUMERO OR
	CN9.CN9_ESPCTR  = '2' AND SZA.ZA_CLIPLAN  = CNA.CNA_NUMERO
	)

INNER JOIN %TABLE:CNB% CNB
ON  CNA.D_E_L_E_T_  = CNB.D_E_L_E_T_
AND CNA.CNA_FILIAL  = CNB.CNB_FILIAL
AND CNA.CNA_CONTRA  = CNB.CNB_CONTRA
AND CNA.CNA_REVISA  = CNB.CNB_REVISA
AND CNA.CNA_NUMERO  = CNB.CNB_NUMERO
AND ( 
	CN9.CN9_ESPCTR  = '1' AND SZA.ZA_RECITEM  = CNB.CNB_ITEM OR
	CN9.CN9_ESPCTR  = '2' AND SZA.ZA_CLIITEM  = CNB.CNB_ITEM
	)

WHERE SZC.%NOTDEL%
AND SZC.ZC_FILIAL = %XFILIAL:SZC%
AND SZC.ZC_COMPETE = %EXP:cCompetenc%
AND SZC.ZC_STATUS = '2'
AND ( 
	CN9.CN9_ESPCTR  = '1' AND CN9.CN9_TPCTO = %EXP:GETMV('MX_TPCTCP')% OR
	CN9.CN9_ESPCTR  = '2' AND CN9.CN9_TPCTO = %EXP:GETMV('MX_TPCTVD')%
	)
AND CN9.CN9_SITUAC = '05'
AND ( 
	CN9.CN9_ESPCTR  = '1' AND CNA.CNA_TIPPLA = %EXP:GETMV('MX_TPPLCP')% OR
	CN9.CN9_ESPCTR  = '2' AND CNA.CNA_TIPPLA = %EXP:GETMV('MX_TPPLVD')%
	)
AND CN9.CN9_ESPCTR = %EXP:cEspCtr%
AND CNA.CNA_XPLHRE <> %EXP:Space( TamSx3( 'CNA_XPLHRE' )[1] )%
AND CNA.CNA_XPLHRE <> CNA.CNA_NUMERO
AND ( 
	CN9.CN9_ESPCTR  = '1' AND CNB.CNB_TE <> %EXP:Space( TamSx3( 'CNB_TE' )[1] )% OR
	CN9.CN9_ESPCTR  = '2' AND CNB.CNB_TS <> %EXP:Space( TamSx3( 'CNB_TS' )[1] )%
	)
AND SUBSTRING( CNA.CNA_PROMED, 5, 2 ) + LEFT( CNA.CNA_PROMED, 4 ) = %EXP:cCompetenc%

ORDER BY CN9.CN9_FILIAL, CN9.CN9_NUMERO, CN9.CN9_REVISA, CNA.CNA_NUMERO, CNB.CNB_ITEM